# Generated by Django 5.1.3 on 2024-12-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='Id_Venta',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
