# Generated by Django 5.1 on 2024-12-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proovedor',
            fields=[
                ('Id_Proovedor', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_producto', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('cant_producto', models.IntegerField()),
                ('horarios', models.DateTimeField()),
                ('telefono', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Proovedor',
                'verbose_name_plural': 'Proovedores',
                'db_table': 'Proovedores',
            },
        ),
    ]
