# Generated by Django 5.1.3 on 2024-12-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proovedores_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proovedor',
            name='horarios',
            field=models.TimeField(),
        ),
    ]
