# Generated by Django 5.1.3 on 2024-12-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proovedores_app', '0002_alter_proovedor_horarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proovedor',
            name='Id_Proovedor',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
